CREATE TABLE Users (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Username TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    PasswordHash TEXT NOT NULL
);

CREATE TABLE Subjects (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name TEXT UNIQUE NOT NULL,
    Description TEXT NOT NULL
);

CREATE TABLE Notes (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Title TEXT NOT NULL,
    Content TEXT NOT NULL,
    User_id INTEGER NOT NULL,
    Subject_id INTEGER NOT NULL,
    Created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(User_id) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY(Subject_id) REFERENCES Subjects(ID)
);

CREATE TABLE Flashcards (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Questions_dict JSONB NOT NULL,
    Answers_dict JSONB NOT NULL,
    User_id INTEGER NOT NULL,
    Subject_id INTEGER NOT NULL,
    Is_public BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY(User_id) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY(Subject_id) REFERENCES Subjects(ID)
);

CREATE TABLE Favourites (
    Flashcard_id INTEGER NOT NULL,
    User_id INTEGER NOT NULL,
    PRIMARY KEY (Flashcard_id, User_id),
    FOREIGN KEY(Flashcard_id) REFERENCES Flashcards(ID) ON DELETE CASCADE,
    FOREIGN KEY(User_id) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE QuizResults (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    User_id INTEGER NOT NULL,
    Flashcard_id INTEGER,
    Score REAL NOT NULL,
    Total_questions INTEGER NOT NULL,
    Completed_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(User_id) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY(Flashcard_id) REFERENCES Flashcards(ID) ON DELETE SET NULL
);